#!/usr/bin/env bash

sudo wget -O vs https://go.microsoft.com/fwlink/?LinkID=760868
sleep 4
sudo apt install vs.deb
sleep 3
sudo add-apt-repository -y "deb https://packages.microsoft.com/repos/vscode stable main "
